# Simpson's Paradox
Use `admission_data.csv` for this exercise.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option("display.max_columns",None)

In [2]:
# Load and view first few lines of datase
df=pd.read_csv("admission_data.csv")

In [4]:
df.head()
# df.info()

   student_id  gender      major  admitted
0       35377  female  Chemistry     False
1       56105    male    Physics      True
2       31441  female  Chemistry     False
3       51765    male    Physics      True
4       53714  female    Physics      True

### Proportion and admission rate for each gender

In [6]:
# Proportion of students that are female
female_proportion = sum(df[df["gender"]=="female"])/sum(df["gender"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [10]:
# Proportion of students that are male
# female_proportion = sum(df[df["gender"]=="male"])/sum(df["gender"])
df[df["gender"]=="male"]

     student_id gender      major  admitted
1         56105   male    Physics      True
3         51765   male    Physics      True
6         25946   male    Physics      True
8         55247   male    Physics     False
9         35838   male    Physics      True
10        40586   male    Physics     False
12        56914   male    Physics      True
13        55248   male    Physics      True
15        37693   male    Physics      True
18        51048   male    Physics      True
19        36390   male    Physics     False
22        42508   male  Chemistry     False
23        51218   male    Physics     False
24        57249   male    Physics      True
27        27555   male    Physics      True
30        49275   male    Physics      True
32        44007   male    Physics      True
34        43863   male    Physics      True
37        29617   male    Physics      True
38        32286   male    Physics     False
40        48706   male    Physics      True
44        44568   male    Physics      True
45        41058   male    Physics      True
46        38571   male    Physics     False
49        24653   male    Physics     False
51        42750   male    Physics      True
54        30552   male    Physics     False
55        43876   male    Physics     False
57        24667   male    Physics      True
58        36617   male    Physics     False
..          ...    ...        ...       ...
429       24519   male    Physics      True
439       52433   male    Physics     False
441       29459   male    Physics      True
442       35264   male    Physics      True
443       41854   male  Chemistry     False
445       34635   male    Physics     False
449       46199   male    Physics     False
450       50686   male    Physics     False
452       48663   male    Physics     False
453       57416   male    Physics     False
454       46267   male    Physics      True
460       51621   male    Physics      True
461       37401   male    Physics     False
465       30815   male    Physics      True
467       26059   male    Physics      True
468       41850   male    Physics      True
470       37902   male    Physics     False
473       36752   male    Physics     False
478       25937   male    Physics      True
480       56173   male    Physics     False
481       32569   male    Physics     False
483       45900   male    Physics      True
484       25710   male    Physics      True
485       50503   male    Physics     False
486       43104   male    Physics      True
489       56171   male    Physics     False
491       25641   male    Physics     False
495       26950   male    Physics     False
498       52067   male    Physics      True
499       50535   male    Physics     False

[243 rows x 4 columns]

In [ ]:
# Admission rate for females

In [ ]:
# Admission rate for males

### Proportion and admission rate for physics majors of each gender

In [ ]:
# What proportion of female students are majoring in physics?

In [ ]:
# What proportion of male students are majoring in physics?

In [ ]:
# Admission rate for female physics majors

In [ ]:
# Admission rate for male physics majors

### Proportion and admission rate for chemistry majors of each gender

In [ ]:
# What proportion of female students are majoring in chemistry?

In [ ]:
# What proportion of male students are majoring in chemistry?

In [ ]:
# Admission rate for female chemistry majors

In [ ]:
# Admission rate for male chemistry majors

### Admission rate for each major

In [ ]:
# Admission rate for physics majors

In [ ]:
# Admission rate for chemistry majors